ERC725Alliance/ERC725

docs/use-cases.md

Caelum labs

---

docs/ERC-725.md
docs/ERC-734.md

Add docs for ERC725 and ERC734

---

contracts/contracts/KeyManager.sol
contracts/package-lock.json
contracts/package.json
contracts/test/key-manager.js

I'm not sure i understood the part with keys correctly. When function e.g. `addKey` is called i'm checking if the key is hash of the caller address, which i saw from the [example](https://github.com/OriginProtocol/origin-playground/blob/master/contracts/KeyHolder.sol#L67) from `origin-playground`.
EDIT:  After a little more research i saw [here](https://github.com/tyleryasaka/identity-proposals/blob/master/contracts/KeyManager.sol#L89) that key can be added on behalf of somebody else who signed this transaction(which is not implemented here). Other than that, is there any other way this key is going to be used?

First part of ERC734

---

contracts/contracts/Identity.sol
contracts/contracts/dummy/Counter.sol
contracts/package-lock.json
contracts/test/identity_test.js

added tests for send/receive ether

---

contracts/contracts/Identity.sol
contracts/contracts/KeyManager.sol
contracts/helpers/forwarder.js
contracts/helpers/utils.js
contracts/package-lock.json
contracts/package.json
contracts/test/forwarder.js
contracts/test/identity_test.js
contracts/test/key-manager.js
contracts/truffle.js
package-lock.json

Truffle 5.0.0

---

contracts/contracts/Identity.sol
contracts/contracts/KeyManager.sol
contracts/helpers/forwarder.js
contracts/helpers/utils.js
contracts/test/forwarder.js
contracts/test/identity_test.js
contracts/test/key-manager.js

Added checks for revert messages

---

contracts/contracts/ERC725.sol
contracts/contracts/Identity.sol
contracts/package-lock.json
contracts/package.json
contracts/test/forwarder.js
contracts/test/identity_test.js
contracts/test/key-manager.js

- Removed web3 1.0 package
- Changed .back value type for `store` in `Identity` contract to `bytes32`
- Removed unused imports

Removed web3 1.0, minor tweaks

---

implementations/.gitignore
implementations/README.md
implementations/package-lock.json
implementations/package.json
implementations/solc.sh

A shell utility to generate the following contracts inner details.
- 🎯   **Bytes4 Functions** selectors per contracts
- 🗄️   **Storage layout** in JSON. 
Useful for contracts using ERC725 as an implementation contract behind proxies. It enables to analyse the layout of the ERC725 contract storage, so to prevent storage collisions between implementations and proxies.
- 🤖  **Contracts deployment + runtime code** (as Hex, EVM opcodes, or `.evm` files)
- **Contracts metadata**
Can be uploaded to decentralised storage networks (IPFS, SWARM...).
Users + interfaces can then query such metadata, and use it as a mean to prove that the bytecode being seen is in fact the product of a compiled ERC725 contract.
- **Gas costs** _(For function with non-dynamic parameters only)_
`npm run solc`
example …

Shell script to generate contract inner-details

---

.github/workflows/build-and-test.yml

A workflow that will execute the following on each push + pull request:
1. Install truffle
2. Install all the npm dependencies
3. Compile all the contracts
4. Run all the truffle tests via `npm test`
The workflow will run 3 times for different versions of node.js (12, 14 and 16).

CI: add truffle build + test workflow

---

implementations/contracts/utils/ERC725Utils.sol

feat: Add `MappAndArrayKey` functions to `ERC725Utils` lib

---

implementations/package-lock.json

You guys didn’t add yourself to the website

Revert "Privatyze.io official request to join the ERC725 Alliance."

---

docs/ERC-725.md
implementations/README.md
implementations/constants.js
implementations/contracts/ERC725YCore.sol
implementations/contracts/constants.sol
implementations/contracts/interfaces/IERC725Y.sol
implementations/package-lock.json
implementations/test/ERC725Y.test.js

feat: getData and setData overloading 

---

.github/workflows/npm-release.yml
implementations/CHANGELOG.md
implementations/contracts/ERC725XCore.sol
implementations/contracts/ERC725YCore.sol
implementations/contracts/helpers/ERC165InterfaceIDs.sol
implementations/contracts/helpers/ERC725XPayableTester.sol
implementations/contracts/helpers/Reader.sol
implementations/contracts/interfaces/IERC725Y.sol
implementations/contracts/utils/ErrorHandlerLib.sol
implementations/contracts/utils/GasLib.sol
implementations/package-lock.json
implementations/package.json

* remove `value` param in `DataChanged` event (#123)

chore: release 3.1.0

---

implementations/contracts/ERC725.sol
implementations/contracts/ERC725Init.sol
implementations/contracts/ERC725InitAbstract.sol
implementations/contracts/ERC725X.sol
implementations/contracts/ERC725XCore.sol
implementations/contracts/ERC725XInit.sol
implementations/contracts/ERC725XInitAbstract.sol
implementations/contracts/ERC725Y.sol
implementations/contracts/ERC725YCore.sol
implementations/contracts/ERC725YInit.sol
implementations/contracts/ERC725YInitAbstract.sol
implementations/contracts/interfaces/IERC725Y.sol

- Contract Cleanup:
- Remove unnecessary import statements
- Fix some natspec wording
- edit variable names

style: clean the contracts (natspec, variable names)

---

implementations/contracts/ERC725Y.sol
implementations/contracts/ERC725YCore.sol
implementations/contracts/ERC725YInit.sol
implementations/contracts/ERC725YInitAbstract.sol
implementations/contracts/interfaces/IERC725Y.sol

style: improve nastpec wording

---

implementations/contracts/ERC725YCore.sol
implementations/contracts/utils/GasLib.sol

- use mixedCase for GasLib function (uncheckedIncrement)

chore: use mixedCase for GasLib function

---

implementations/contracts/ERC725XCore.sol
implementations/test/ERC725X.behaviour.ts

Changing "Unknow Error" to "Unknown Error" in ERC725XCore.sol as well as in ERC725X.behaviour.ts

[Code Documentation] ERC725XCore.sol - "Unknow Error" should be "Unknown Error"

---

docs/ERC-725.md

Improving the ERC725 specs with the section needed to be finalized also in EIP repo.
with @frozeman 🤝

docs: improve ERC725 specs

---

implementations/CHANGELOG.md
implementations/package-lock.json
implementations/package.json

- Preparing the changelog.
- Bumping the version: 3.2.0 -> 4.0.0

chore: prepare release 4.0.0

---

docs/ERC-725.md

- Mark the correct requirements of the standard and the functions
- Add example for the code snippet as mentioned by @frozeman in [previous PR](https://github.com/ERC725Alliance/ERC725/pull/177/files#r1009181514) 
- Correct reference of `to` param to `target`

docs: improve requirements for ERC725 specs + examples

---

implementations/constants.js

- add custom errors and event signatures to `constants.js`

chore: add errors and event signatures to `constants.js`

---

implementations/.editorconfig
implementations/.prettierrc
implementations/constants.js
implementations/test/ConstantsChecker.test.ts
implementations/test/ERC725.test.ts
implementations/test/ERC725X.behaviour.ts
implementations/test/ERC725X.test.ts
implementations/test/ERC725Y.behaviour.ts
implementations/test/ERC725Y.test.ts
implementations/test/fixtures.ts

- update prettier config.
- create `.editorconfig` file.
- applied prettier with new style rules on all TS/JS files in test + `constant.js`

chore: add editor config + update prettier settings

---

implementations/constants.js
implementations/contracts/ERC725XCore.sol
implementations/contracts/ERC725YCore.sol
implementations/contracts/errors.sol
implementations/test/ERC725Y.behaviour.ts

- Remove unnecessary typecasting
- Inline unchecked increment
- Remove parameters from error (ERC725Y) to keep consistency with ERC725X
- Add missing custom errors to constants.js

chore: optimize for gas cost

---

implementations/CHANGELOG.md
implementations/package.json

chore: prepare 5.0.0 release

---

implementations/slither.config.json

Add a new file `slither.config.json` to run Slither locally via the CLI (in preparation of adding it via the CI).

chore: add `slither.config.json` to run Slither locally

---

implementations/package.json

build!: bump `@openzeppelin` to 4.9.1 in `package.json`

---

implementations/CHANGELOG.md
implementations/package.json

chore: prepare 5.1.0 release

---

implementations/contracts/ERC725XCore.sol
implementations/contracts/custom/OwnableUnset.sol
implementations/test/ERC725.test.ts

chore: [C4] Add Gas optimization fixes

---

docs/ERC-725.md
implementations/CHANGELOG.md
implementations/constants.js
implementations/contracts/interfaces/IERC725X.sol
implementations/package-lock.json
implementations/package.json

- Update `Executed` event in ERC725X to index `selector` instead of `value` ([#246](https://github.com/ERC725Alliance/ERC725/pull/246))
- Update `ContractCreated` event in ERC725X to index `salt` instead of `value` ([#246](https://github.com/ERC725Alliance/ERC725/pull/246))

chore: release 7.0.0

---

implementations/contracts/ERC725YCore.sol

Currently, it is not possible to call the `setDataBatch` function internally because this function contains the `onlyOwner` modifier, which check for the caller.
This prevents inheriting contracts from calling this function, and therefore make them have to re-write the same `for` loop again.
Moreover, this appears to be inconsistent with `ERC725XCore`, as this contract contains an internal version of `_executeBatch(...)`.
Add an internal `_setDataBatch(...)` function to enable this behaviour and re-using the function logic for easiness, without runnning through the `onlyOwner` modifier blocker.

feat: add internal `_setDataBatch` function without owner modifier

---

docs/ERC-725.md

Fixes a link reference to smart contract implementations

fix: link to implementations folder;
