ERC725Alliance/ERC725

- contracts/contracts/Identity.sol
- contracts/contracts/KeyManager.sol
- contracts/helpers/forwarder.js
- contracts/helpers/utils.js
- contracts/package-lock.json
- contracts/package.json
- contracts/test/forwarder.js
- contracts/test/identity_test.js
- contracts/test/key-manager.js
Closes #13 
Constructors are not supported by forwarder, so i had to introduce `initialize` function along with `initialized` variable.
Between contract deployment and initialization there is time available for malicious actor to call `initialize` before the person that deployed the contract. For the deployer, they will only lose the money used for deployment, they can always deploy another one. This is possible in theory, in practice - very unlikely, but still.
This can be solved by creating another contract that will create and initialize the desired contract inside the same function. Thoughts?
> Forwarder contract

- contracts/contracts/ERC725.sol
- contracts/contracts/Identity.sol
- contracts/contracts/KeyManager.sol
- contracts/contracts/dummy/Counter.sol
- contracts/contracts/truffle/Migrations.sol
- contracts/test/forwarder.js
- contracts/truffle.js
Closes #18 
Solium still doesn't fully support Solidity 0.5, so it will find some errors.
@tyleryasaka Whats the reason behind value of `store` mapping being `bytes32` and not `address` in  `Identity` contract?
> Upgraded to solc 0.5.1

- contracts/contracts/ERC725.sol
- contracts/contracts/Identity.sol
This changes the data set from `bytes32 => bytes32` to `bytes32 => bytes`, which makes it a lot more flexible.
> Using bytes, instead of bytes32

- implementations/contracts/ERC725/ERC725X.sol
- implementations/contracts/ERC725/ERC725Y.sol
This solves a solc compile error `TypeError: Linearization of inheritance graph impossible` by inheriting the "most base-like" contracts first to prevent errors from inheriting contract. 
See a similar fix here https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1128
---
I came across this issue with a contract that has a token implementation from OpenZeppelin and `ERC725Y` as part of its inheritance graph.
> fix: ERC725X and ERC725Y inherit Ownable first

- implementations/README.md
Just cleaned the header in the README under /implementations
> Fix Interface ID header in docs

- implementations/contracts/utils/ERC725Utils.sol
Bug Found by @mattgstevens 
Will need to do some changes in the `LSP1UniversalReceiverDelegateUP` and `LSP1UniversalReceiverDelegateVault` contracts after releasing
> fix: fix appendix overwriting bug in ERC725Utils

- implementations/contracts/LSP1UniversalReceiver.sol
- Use **ERC165Checker** instead of the old method to avoid calling a non-existing function and reverting 
- Switch from checking if the length is 20 **to** checking if the length is more than 20 and taking the first 20 bytes as address
**Motivation**
- This way we can make the `universalReceiver` function more **flexible** and **functional** even if the user has set wrong data in his **UniversalProfile**
> feat: optimize universalReceiver function (more flexible)

- implementations/contracts/ERC725AccountInit.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725YInit.sol
- implementations/package-lock.json
> fix: initializer re-entrancy vulnerability from OZ (4.4.1)

- implementations/README.md
As mentioned in the PR name, it removes the details related to **ERC725Account** contracts, **LSP1** and **ERC1271** in the contracts README, as these contracts are removed from the repo in PR #82
> chore: remove ERC725Account & LSP1 details from README

- implementations/constants.js
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/helpers/Return.sol
- implementations/contracts/utils/ErrorHandlerLib.sol
- implementations/reduce-artifacts.js
- implementations/test/ERC165InterfaceIDs.test.js
- implementations/test/ERC725X.test.js
- implementations/test/ERC725Y.test.js
- implementations/test/helpers.js
- implementations/truffle-config.js
With the introduction of custom errors in solc 0.8.4, the current way of handling a reverted contract call is incorrect and will not bubble all custom errors. This is due to a length check that worked for error strings, but an encoded custom error can be less than 68 bytes.
By creating a library with an internal function, this can save some code duplication in this repo, and used other contracts that may need to handle errors in a similar way (for example LSP6KeyManager).
> ERC725 execute handle custom errors

- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
Mark the `initialize(...)` as `internal` in the `...InitAbstract` contracts, so to avoid function overloading in contracts that inherit from them.
This remove these functions to be considered as _function overloading_ by the SOlidity compiler and to appear in the generated JSON ABI.
Also reduce size of contract bytecode as follow:
- `ERC725XInit`: - 1,394 bytes
- `ERC725YInit`: -118 bytes
- `ERC725Init`: -1,272 bytes
> fix: mark `initialize(...)` as internal for `onlyInitializing` functions

- implementations/contracts/ERC725YCore.sol
- implementations/contracts/utils/GasLib.sol
To import the library in [lsp-smart-contract](https://github.com/lukso-network/lsp-smart-contracts) repo and apply the same pattern in the Key Manager and all other contracts needed.
The change in ERC725Y + LSP6KeyManager could save up to **~2,000** gas in an LSP7Token transfer scenario.
> perf: add unchecked for iterator

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInitAbstract.sol
- Removing the import of ERC165 from Core versions. (To not conflict when inheriting in other superior contracts).  
- Removing ERC165Storage and replacing it with overriding `supportsInterface(...)` function which reduces deployment cost by **~30,100 gas units** for each contract.
> refactor: override `supportsInterface` instead of ERC165Storage

- implementations/contracts/constants.sol
- implementations/contracts/helpers/ERC165InterfaceIDs.sol
The file `constants.sol` imports the interfaces `IERC725X` and `IERC725Y`. (previously used when interface IDs were calculated via `type(IERC725X).interfaceId`.
The `constants.sol` file should only contain constants values, and not import anything.
So moved the interfaces being imported outside of this constant file and placed them inside the helper contract `ERC165InterfaceIDs.sol` (used to ensure interface ID are correctly hardcoded as iiterals in Solidity and Javascript).
> refactor: remove importing interfaces inside `constants.sol`

- implementations/contracts/utils/OwnableUnset.sol
Change visibility `_setOwner(...)` function `private` -> `internal`, to enable derived contract to override or implement different behaviours for transferring ownership of contracts.
> refactor: mark _setOwner(...) function as internal

- implementations/contracts/ERC725XCore.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/truffle-config.js
Reduce gas usage in `ERC725X.execute(...)` by emitting the `Executed(...)` event with only the first 4 bytes of the `_data` payload given to the function (= function selector).
Interfaces can get more details about the function being executed by grabbing subsequent events emitted in the contract being interacted with.
> refactor: use bytes4 selector in Executed event

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/helpers/Contract.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/contracts/interfaces/IERC725Y.sol
- Re-ordering the inherited contracts from most base to most derive
- Inherit the **IERC165** at the interface level.
> fix: inherit most base to most derived

- docs/ERC-725.md
- Adding function signature for ERC725Y functions
- Add a note to use specific notations when calling ERC725Y overloaded functions
- Mark standard as final instead of draft
- Change the terms keys and values to dataKeys and dataValues.
- Change the term key/value store to data key/value store. (Use key/value store instead of key-value store)
- Edit `Executed` event to use bytes4 instead of bytes
> docs: improve ERC725Y section

- implementations/contracts/ERC725XCore.sol
- implementations/test/ERC725X.test.js
The low level operations `staticcall` and `delegatecall` do not allow to pass some value.
Implement a `require(...)`  check to verify that no value is being passed in the `_value` parameter if the operation type is `STATICCALL = 3` or `DELEGATECALL = 4`
> fix: check for zero value with staticcall and delegatecall

- docs/ERC-725.md
- implementations/contracts/interfaces/IERC725X.sol
Improve documentation for `ERC725X.execute(...)` with the following terms:
- replace `value` -> `amount` in docs
- specify **unit for value transfer = Wei**
- replace `ETH` -> `native tokens` to make it more generic
**Other fixes**
- replaced `contract data` -> `bytecode of the contract`
> docs: improve documentation for value transfer + contract bytecode

- implementations/contracts/ERC725XCore.sol
- implementations/test/ERC725X.test.js
The current implementation of `execute(...)` function in `ERC725XCore` does not use the `_to` address field if the operation type is CREATE or CREATE2.
This mean that anyone can create/deploy a contract while specifying any address in the `_to` parameter (as this address will not be used).
Although this is the expected behaviour, this is semantically incorrect. The Ethereum protocol specify that for contract creation, **the `to` address field must be empty** (see [Ethereum Yellow Paper for reference](https://ethereum.github.io/yellowpaper/paper.pdf), page 4, **section 4.2) The Transaction**, bullet point **to:**).
Add an additional check for the `_to` parameter when `_operationType == CREATE` or `_operationType == CREATE2`, to ensure that `address(0)` is specified.
> refactor: check for zero address in ERC725X for operation CREATE or CREATE2

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/custom/Initializable.sol
- implementations/contracts/custom/OwnableUnset.sol
- implementations/package-lock.json
- implementations/package.json
- Moving OwnableUnset to `custom` folder
- Adding `Initializable` contract to `custom` folder where this version has the booleans checks `initialized` and `initializing` public for making the implementation as generic as possible. One example would be to check these booleans by external contracts for security reasons when performing delegatecall.
> chore: add custom `Initializable` contract 

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725YCore.sol
- Replace `super` keyword with `ERC165` to point to the right contract to call.
Saves a few hundred gas.
> fix: replace `super` with `ERC165` in `supportsInterface`

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725YCore.sol
- Reverting PR #116 as it turns out that `super` is useful for contracts who inherit ERC725 contracts, not just inherited contracts by ERC725.
It is necessary to keep `super`.
> revert: (PR#116) use `super` instead of `ERC165` for `supportsInterface(..)`

- implementations/contracts/ERC725XCore.sol
> refactor!: remove `owner()` check for delegatecall + add WARNING comment

- implementations/contracts/ERC725YCore.sol
- implementations/contracts/interfaces/IERC725Y.sol
The `DataChanged` event emits the updated value every time some data key is changed on ERC725Y.
This makes interaction with the ERC725Y key-value store expensive, especially in scenarios where:
- the `_value` contains a lot of bytes (_e.g:_ a JSONURL containing around 90 bytes).
- the caller call `setData(bytes32[],bytes[])` to update multiple data keys at once. Depending on the size of each value in the data key-value pairs, will make the call very expensive and will consume a lot of gas.
Remove the `value` parameter from the `DataChanged` event in ERC725Y.
Below is a table summary of the gas saving per bytes32 words. (**NB:** same gas savings apply, whether the data key is set for the 1st time, or updated).
| number of bytes  | gas cost `DataChanged(bytes32,bytes)` - **2 x params** | …
> refactor!: save gas on ERC725Y by removing `value` parameter in `DataChanged` event

- docs/ERC-725.md
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/interfaces/IERC725Y.sol
> Changes in this file a more visible by looking at the files themselves, rather than the diff
> https://github.com/ERC725Alliance/ERC725/blob/style/erc725y/implementations/contracts/interfaces/IERC725Y.sol
> https://github.com/ERC725Alliance/ERC725/blob/style/erc725y/docs/ERC-725.md#erc725y
- change order of the definitions for ERC725Y functions to read/write data key(s).
1. functions to read/write a single data key defined **first**
2. functions to read/write multiple data key defined **second**
As per the following order:
```
getData(bytes32)
setData(bytes32,bytes)
getData(bytes32[])
setData(bytes32[],bytes[])
```
> style: move get / set data single function first

- implementations/contracts/utils/ErrorHandlerLib.sol
When running Slither, the static analysis reports that the value by `ErrorHandlerLib.revertWithParsedError(...)` is ignored and not used.
```
ERC725XCore.executeCall(address,uint256,bytes,uint256) (node_modules/@erc725/smart-contracts/contracts/ERC725XCore.sol#131-145) ignores return value by ErrorHandlerLib.revertWithParsedError(result) (node_modules/@erc725/smart-contracts/contracts/ERC725XCore.sol#141)
ERC725XCore.executeStaticCall(address,bytes,uint256) (node_modules/@erc725/smart-contracts/contracts/ERC725XCore.sol#154-166) ignores return value by ErrorHandlerLib.revertWithParsedError(result) (node_modules/@erc725/smart-contracts/contracts/ERC725XCore.sol#162)
ERC725XCore.executeDelegateCall(address,bytes,uint256) (node_modules/@erc725/smart-contracts/contracts/ERC725XCore.sol#177-190 …
```
> fix: remove return definition in ErrorHandlerLib.revertWithParsedError(…)

- implementations/contracts/custom/OwnableUnset.sol
- optimize `onlyOwner` modifier in OwnableUnset contract.
This reduces the contract size as the require check will be called not implemented as code in each function.
> refactor: optimize `onlyOwner` modifier in OwnableUnset contract

- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725YInit.sol
- implementations/test/ERC725X.test.js
- implementations/test/ERC725Y.test.js
Currently, the base contract version (implementation to be used behind proxy) needs to be initialized after deployment. This create a race condition via 2 transactions.
> fix!: lock base `ERC725XInit` and `ERC725YInit` contracts on deployment

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/custom/OwnableUnset.sol
- implementations/test/ERC165InterfaceId.test.ts
- implementations/test/ERC725.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725X.test.ts
- implementations/test/ERC725Y.behaviour.ts
- implementations/test/ERC725Y.test.ts
- add additional checks to prevent contract owner to be set as `address(0)` when deploying/initializing the contract.
- start simple test suite for testing `ERC725.sol` and `ERC725Init.sol` contract.
> fix: [QSP-4] prevent `address(0)` to be set as contract owner on deployment

- implementations/contracts/ERC725YCore.sol
- implementations/contracts/interfaces/IERC725Y.sol
- implementations/test/ERC725Y.behaviour.ts
In this PR a new parameter is added to the `DataChanged` event, `dataValue`.
Also the tests are fixed in order to take into account `dataValue` whenever it is checked if the event `DataChanged` was emitted.
> feat!: add `bytes dataValue` parameter to `DataChanged` event in ERC725Y

- implementations/.prettierrc
- implementations/contracts/ERC725XCore.sol
- implementations/test/ERC725X.behaviour.ts
- Improve the internal functions of `ERC725XCore.sol`, so to allow better and easier overriding of the `execute(...)` function.
- mark the `internal` functions as `virtual`, so they can be overridden individually.
> made in peer programming with @YamenMerhi 🤝 using [VS Code Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack) extension.
> refactor: improve internal functions of `ERC725XCore`

- implementations/CHANGELOG.md
- implementations/package-lock.json
- implementations/package.json
> chore: prepare release 3.2.0

- README.md
- docs/ERC-734.md
> docs: remove space between "ERC" and "725" in main README page

- implementations/contracts/ERC725XCore.sol
This PR fixes some potential issues by emitting the `Executed(..)` event before the external calls inside the internal methods: `_executeCall(..)`, `_executeStaticCall(..)` and `_executeDelegateCall(..)`.
This is done in order to preserve the check-effect-interaction pattern, emitting an event being a effect and the external calls being interactions.
> fix: emit `Executed(..)` event before the external calls

- implementations/contracts/ERC725YCore.sol
In `ERC725YCore` change variable name from `store` -> `_store` as this variable is `internal`.
> style: add underscore to variable name `store` -> `_store`

- docs/ERC-725.md
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/constants.sol
- implementations/contracts/custom/OwnableUnset.sol
- implementations/contracts/errors.sol
- implementations/contracts/helpers/Reader.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/hardhat.config.ts
- implementations/test/ERC725.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725X.test.ts
- implementations/test/ERC725Y.behaviour.ts
- implementations/test/ERC725Y.test.ts
- ⚠️ replace revert reason strings by custom errors in `ERC725XCore` and `ERC725YCore`. All errors are listed in `errors.sol`.
This reduces the deployment cost of the contracts by around 200,00 gas. See table summary below.
- ⚠️  rename the `uint256` constants for each OPERATION_TYPE by adding the operation number inside the constant name. `OPERATION_CALL` -> `OPERATION_0_CALL`.
- remove modifier to inline owner is not zero address check inside constructor / initializer.
- delete comments that aim to create sections _e.g: public functions, internal functions, overriden functions, etc...)_. Remove these comments in favour of following the Solidity style guide: 
- added Natspec comments for newly created custom errors.
- improve descriptions of existing Natspec docs comments + descriptions …
> perf!: replace error strings by custom errors + use `enum` for `OPERATION_TYPE`

- docs/ERC-725.md
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/test/ERC725X.behaviour.ts
-  add `salt` parameter to the `ContractCreated` event in ERC725X
-  add tests
- adjust the specs accordingly
> refactor!: add `salt` parameter to the `ContractCreated` event in ERC725X

- implementations/contracts/ERC725XCore.sol
- implementations/test/ERC725X.behaviour.ts
When a child contract inherits ERC725X and override the public `execute` functions (standards and batch), if `super` is used in the function body, the `onlyOwner` modifier will run twice.
Move the logic from the `execute` (standard and batch) inside their own internal function. This allow to easily override the `internal` functions in child contract to modify the core logic only, without adding duplicate checks.
> refactor: move ERC725X logic inside internal functions

- docs/ERC-725.md
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/errors.sol
- implementations/contracts/interfaces/IERC725Y.sol
- implementations/test/ERC725Y.behaviour.ts
- mark `setData(..)` as payable
- Add tests for reverting when sending value
> refactor!: mark `setData(..)` as payable

- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/errors.sol
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725Y.behaviour.ts
When the batch functions below are called with empty array parameters:
- `ERC725X.execute(uint256[],address[],uint256[],bytes[])`
- `ERC725Y.setData(bytes32[],bytes[])`
Nothing happen and the contract call return successfully and silently. Reason being the internal function never enter inside the `for` loops.
Add extra checks to test for empty array parameters in these batch functions.
Add tests when:
- all the array parameters are empty arrays.
- at least one of the array parameters is an empty array.
> fix: add check for empty array parameters in batch `ERC725X.execute(uint256[],address[],uint256[],bytes[])` / `ERC725Y.setData(bytes32[],bytes[])`

- implementations/package-lock.json
- implementations/package.json
Upgrade dependencies to fix Dependabot Security warning for: _"flat vulnerable to Prototype Pollution"_
> NB: hardhat 2.13.1 adds supports for Shangaï upgrade.
> see details: https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.13.1
Upgrade the following dependencies to fix dependabot security warnings (screenshot below).
- `@openzeppelin/contracts` and `@openzeppelin/contracts-upgradable`: `4.7.3` --> upgraded to `4.8.3`
- `hardhat`: `2.10.1` --> upgraded to `2.13.1`. 
- `@nomicfoundation/hardhat-toolbox`: `2.0.0` --> `2.0.2`
> build: upgrade dependencies to fix dependabot security warnings

- docs/ERC-725.md
- implementations/constants.js
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/constants.sol
- implementations/contracts/errors.sol
- implementations/contracts/helpers/ConstantsChecker.sol
- implementations/contracts/helpers/ERC725YReader.sol
- implementations/contracts/helpers/ERC725YWriter.sol
- implementations/contracts/helpers/Reader.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/contracts/interfaces/IERC725Y.sol
- implementations/test/ConstantsChecker.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725Y.behaviour.ts
- Remove function overloading
- Change in the interfaceId
- Change in the way js libraries call ERC725 functions
Function overloading is not supported in many blockchain programming languages (vyper, cairo), which can create interoperability issues. To ensure language independence and promote interoperability, it was decided to remove function overloading and simply rename the functions to include the word "batch" when taking an array.
> refactor!: remove function overloading

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YInit.sol
- implementations/test/ERC725.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725X.test.ts
- implementations/test/ERC725Y.behaviour.ts
- implementations/test/ERC725Y.test.ts
Allow the contract to be funded on deployment via `constructor` or `initialize(...) public` functions.
> feat: allow to fund ERC725 contracts on deployment

- implementations/contracts/ERC725XCore.sol
Use explicit `return` statements inside the `internal` functions of `ERC725XCore`, so to distinguish visually in the code what is being returned by the function.
> refactor: use explicit `return` statements in `ERC725XCore`

- implementations/constants.js
- implementations/contracts/constants.sol
- implementations/contracts/helpers/ConstantsChecker.sol
- implementations/test/ConstantsChecker.test.ts
**Deprecate constants `EXECURTE_SELECTOR`, `EXECUTE_BATCH_SELECTOR`, `SETDATA_SELECTOR` and `SETDATA_BATCH_SELECTOR`.**
Prior to v5.0.0, it was not possible to access the selector for the overloaded functions with `.selector` syntax in Solidity.
Therefore, these selectors were saved in solidity `bytes4 constant`.
Since v5.0.0, overloaded functions have been removed, and it now possible to access these selectors via `setData.selector` and `setDataBatch.selector` in Solidity.
Remove these constants from the `constants.sol` file.
> refactor!: remove deprecated constants for overloaded function selectors

- implementations/package-lock.json
- implementations/package.json
Bump default version of `@openzeppelin/contracts` and `@openzeppelin/contracts-upgradable` from `4.9.1` to `4.9.2` in `package.json`.
> build: upgrade `@openzeppelin/contracts` to 4.9.2

- implementations/README.md
Fix incorrect ERC165 interface IDs for ERC725X and ERC725Y in the README under the `implementations/` folder.
> docs: update interface ID table + add missing external links

- implementations/CHANGELOG.md
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/errors.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/contracts/interfaces/IERC725Y.sol
- implementations/package-lock.json
Improve all the Natspec comments across the Solidity files, so that projects that inherit from them like https://github.com/lukso-network/lsp-smart-contracts can parse the Natspec docs and auto-generate Markdown dev docs.
https://github.com/lukso-network/lsp-smart-contracts/pull/638
> docs: improve Natspec comments of smart contracts

- implementations/CHANGELOG.md
- implementations/package-lock.json
- implementations/package.json
Prepare a new minor release that includes better Natspec comments, so that they can better used to render developer docs in package that use `@erc725/smart-contracts` as a dependency.
See https://github.com/lukso-network/lsp-smart-contracts/pull/638
- Bump version in `package.json` and `package-lock.json` from `5.1.0` > `5.2.0`
- Add release details in `CHANGELOG.md`
> chore: prepare release 5.2.0

- implementations/CHANGELOG.md
- implementations/package-lock.json
- implementations/package.json
- Bump version of `@openzeppelin/contracts` dependency from `4.9.2` to `4.9.3` in `package.json`
> build: upgrade OpenZeppelin contracts to 4.9.3

- implementations/CHANGELOG.md
- implementations/README.md
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/errors.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/contracts/interfaces/IERC725Y.sol
- implementations/package-lock.json
- implementations/package.json
- Bump `@openzeppelin/contracts` from `4.9.2` to `4.9.3`.
- Improve Natspec comments across all contracts, so that they can be used and parsed via `@inheritdocs` tag.
> chore: release 5.2.0

- .github/workflows/solc_version.yml
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/custom/OwnableUnset.sol
- implementations/contracts/errors.sol
- implementations/test/ERC725.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725X.test.ts
- implementations/test/ERC725Y.behaviour.ts
- implementations/test/ERC725Y.test.ts
- **Fixed:** minimum solc version required for ERC725Y is now `0.8.4` because of the use of custom errors: https://github.com/ethereum/solidity/releases/tag/v0.8.4
- **Refactor:** minimum solc version required for ERC725X and ERC725 is now `0.8.5` because of the use `bytes` to `bytesN` conversion: https://github.com/ethereum/solidity/releases/tag/v0.8.5
- Increase minimum `solc` compiler version because of full usage of custom `error` (currently states `pragma solidity ^0.8.0`
Replace revert reason strings with custom errors for `OwnableUnset` and `address(0)` check on `transferOwnership()`, `constructor` and `initialize(address)` functions.
This reduces the deployment cost of an `ERC725` smart contract by -58,427 gas.
> refactor: use custom error for `onlyOwner` and `address(0)` check

- implementations/contracts/ERC725XCore.sol
- implementations/contracts/interfaces/IERC725X.sol
Add `@custom:warning` tag about using `msg.value` with delegate call (single or batch).
> docs: add Natspec warning comment about using `msg.value` with delegatecall

- implementations/.solhint.json
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/helpers/ConstantsChecker.sol
- implementations/contracts/helpers/CustomRevertTest.sol
- implementations/contracts/helpers/ERC725XPayableTester.sol
- implementations/package-lock.json
- implementations/package.json
Fix solhint linter errors such as:
- unused imports or global imports
- add `// solhint-disable-next-line comments` for Mock contracts for `custom-error` rule.
Improve code layout for some `if` statements checks to use `if` blocks for consistency and better readability.
- Upgrade solhint version to `3.6.2`
- add solhint settings to throw an error for unused or global imports
> build: upgrade solhint + fix solidity linter errors

- implementations/CHANGELOG.md
- implementations/package-lock.json
- implementations/package.json
- Bump version in `package.json` from `5.2.0` to `6.0.0`.
- Add release details in `CHANGELOG.md`
> chore: prepare release 6.0.0

- .github/workflows/solc_version.yml
- implementations/.solhint.json
- implementations/CHANGELOG.md
- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XCore.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YCore.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
- implementations/contracts/custom/OwnableUnset.sol
- implementations/contracts/errors.sol
- implementations/contracts/helpers/ConstantsChecker.sol
- implementations/contracts/helpers/CustomRevertTest.sol
- implementations/contracts/helpers/ERC725XPayableTester.sol
- implementations/contracts/interfaces/IERC725X.sol
- implementations/package-lock.json
- implementations/package.json
- implementations/test/ERC725.test.ts
- implementations/test/ERC725X.behaviour.ts
- implementations/test/ERC725X.test.ts
- implementations/test/ERC725Y.behaviour.ts
- implementations/test/ERC725Y.test.ts
- Replace revert reason strings by custom `error` in `OwnableUnset` and inside `constructor` / `initialize(...)` functions for `address(0)` checks ([#236](https://github.com/ERC725Alliance/ERC725/pull/236))
- Implement Gas Optimisations & QA from Code4Rena audit contest ([#235](https://github.com/ERC725Alliance/ERC725/pull/235))
- fix minimum pragma `solc` version required to `0.8.4` for ERC725Y and `0.8.5` for ERC725X and ERC725 ([1afd0dd](https://github.com/ERC725Alliance/ERC725/pull/236/commits/1afd0dd1af4d7008907c0fd74cf0ad3fdf3ddbe5) and [dbc0f61](https://github.com/ERC725Alliance/ERC725/pull/236/commits/dbc0f61027b81a2a583cf25f1e2af4da4897b955))
> chore: release v6.0.0

- docs/ERC-725.md
- implementations/constants.js
- implementations/contracts/interfaces/IERC725X.sol
- Update `Executed` so that `selector` is indexed over `value` 
- Update `ContractCreated ` so that `salt` is indexed over `value`
> refactor: index selector over value in Executed event

- implementations/CHANGELOG.md
- implementations/package-lock.json
- implementations/package.json
- Prepare a new minor release
- Bump version in `package.json` and `package-lock.json` from `6.0.0` > `7.0.0`
- Add release details in `CHANGELOG.md`
> chore: prepare release 7.0.0

- docs/ERC-725.md
> docs: Re-arrange ERC725 specs section

- implementations/package-lock.json
- implementations/package.json
Upgrade `solidity-bytes-utils` to latest patch release. This remove the truffle-hd-wallet from the dependencies installed when a project uses this package within its project.
[`package.json` of v0.8.0](https://github.com/GNSPS/solidity-bytes-utils/blob/v0.8.0/package.json)
[`package.json` of v0.8.3](https://github.com/GNSPS/solidity-bytes-utils/blob/v0.8.3/package.json)
> build: upgrade `solidity-bytes-utils` dependency to latest patch release

- implementations/contracts/ERC725.sol
- implementations/contracts/ERC725Init.sol
- implementations/contracts/ERC725InitAbstract.sol
- implementations/contracts/ERC725X.sol
- implementations/contracts/ERC725XInit.sol
- implementations/contracts/ERC725XInitAbstract.sol
- implementations/contracts/ERC725Y.sol
- implementations/contracts/ERC725YInit.sol
- implementations/contracts/ERC725YInitAbstract.sol
Add suggestions from Milo Truck audit on ERC725 smart contracts (including typos)
> fix: add warning comments about `constructor` / `initialize` functions being payable by default

- implementations/.tool-versions
- implementations/package.json
Hardhat was signaling warnings that this repository is using a version of nodejs that is not maintained and supported by Hardhat anymore. In fact, the `.tool-versions` file list node v16. See Node.js releases for more details. https://github.com/nodejs/Release
- change to node v18, which is the currently supported version
> build: upgrade `.tool-versions` file to use nodejs version supported by Hardhat dependency
